config/routes.rb
Rails.application.routes.draw do
  root 'public/customers#about'
  namespace :public do
    devise_for :customers
    get '/top', to: 'customers#top', as: "top"
    resources :customers, only: [:show, :edit, :update]
    put '/customers/:id/hide', to: 'customers#hide', as: 'destroy'
    resources :rooms, only: [:create, :show]
    resources :messages, only: [:create, :destroy]
    resources :dogs, only: [:new, :create, :show, :edit, :update, :destroy]
    get '/posts/newimage', to: 'posts#newimage', as: "newimage"
    get '/posts/newvideo', to: 'posts#newvideo', as: "newvideo"
    resources :posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :relationships, only: [:create, :destroy]
    get '/followers', to: 'relationships#followers', as: "followers"
    get '/follows', to: 'relationships#follows', as: 'follows'
    resources :notifications, only: :index
    get '/notification', to: 'notifications#hide', as: 'hide'
    get '/search', to: 'search#search'
  end

  namespace :admin do
    devise_for :admins
    resources :dog_breeds, only: [:index, :create, :destroy]
    resources :customers, only: [:index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :dogs, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :introduction, length: { maximum: 100 }
  # ユーザー理論削除
  def active_for_authentication?
    super && (is_active == "有効")
  end
  enum is_active: { "退会": false, "有効": true }

  # いいね機能
  has_many :favorites, dependent: :destroy
  # DM機能
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries
  # フォロー機能
  has_many :relationships
  # 画像投稿
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :profile_image, ProfileImageUploader
  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin_admin!
  def index
    @customers = Customer.page(params[:page]).order('created_at DESC').per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "登録情報を変更しました。"
    render 'edit'
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :date_of_birth, :introduction, :cover_image, :profile_image, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-5 mb-3">
  <h1>会員情報編集</h1>
    <%= form_for @customer, url: admin_customer_path do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%= flash[:notice] %>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :name, 'ニックネーム' %>
        </div>
        <div class="col-md-3">
          <%= f.text_field :name,class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :date_of_birth, '生年月日' %>
        </div>
        <div class="col-md-4">
          <%= raw sprintf(
                f.date_select(
                  :date_of_birth,
                  use_month_numbers: true,
                  start_year: 1930,
                  end_year: (Time.now.year),
                  default: Date.new(2000, 1, 1),
                  date_separator: '%s'),
                '年 ', '月 ') + '日' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :introduction, '自己紹介分' %>
        </div>
        <div class="col-md-9">
          <%= f.text_area :introduction,class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :cover_image, 'カバー画像' %>
        </div>
        <div class="col-md-3">
          <%= image_tag @customer.cover_image.url, id: :img_prev7 %><br>
          <%= f.file_field :cover_image, id: :customer_img7 %>
          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#img_prev7').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $('#customer_img7').change(function(){
                readURL(this);
            });
          });
          </script>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :profile_image, 'プロフィール画像' %>
        </div>
        <div class="col-md-3">
          <%= image_tag @customer.profile_image.url, id: :img_prev8 %><br>
          <%= f.file_field :profile_image, id: :customer_img8 %>
          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#img_prev8').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $('#customer_img8').change(function(){
                readURL(this);
            });
          });
          </script>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :is_active, '会員ステータス' %>
        </div>
        <div class="col-md-3">
          <div class="field">
            <label><%= f.radio_button :is_active, "有効" %>有効</label>
            <label><%= f.radio_button :is_active, "退会" %>退会済み</label>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.submit '変更を保存',class: 'btn btn-outline-secondary' %>
        </div>
    <% end %>
      </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2>会員一覧</h2>
  全<%= @customers.count %>件登録
  <table class="table table-hover bg-white">
	<tbody>
      <% @customers.each do |customer| %>
        <tr>
		  <th>
		    <%= customer.name %> 様
		  </th>
      <th><%= link_to "編集",edit_admin_customer_path(customer),class: 'btn btn-outline-secondary' %>
      </th>
		</tr>
      <% end %>
    </tbody>
  </table>
  <div class="col-md-4 offset-4">
  <%= paginate @customers %>
</div>
</div>