config/routes.rb
Rails.application.routes.draw do
  root 'public/customers#about'
  namespace :public do
    devise_for :customers
    get '/top', to: 'customers#top', as: "top"
    resources :customers, only: [:show, :edit, :update]
    put '/customers/:id/hide', to: 'customers#hide', as: 'destroy'
    resources :rooms, only: [:create, :show]
    resources :messages, only: [:create, :destroy]
    resources :dogs, only: [:new, :create, :show, :edit, :update, :destroy]
    get '/posts/newimage', to: 'posts#newimage', as: "newimage"
    get '/posts/newvideo', to: 'posts#newvideo', as: "newvideo"
    resources :posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :relationships, only: [:create, :destroy]
    get '/followers', to: 'relationships#followers', as: "followers"
    get '/follows', to: 'relationships#follows', as: 'follows'
    resources :notifications, only: :index
    get '/notification', to: 'notifications#hide', as: 'hide'
    get '/search', to: 'search#search'
  end

  namespace :admin do
    devise_for :admins
    resources :dog_breeds, only: [:index, :create, :destroy]
    resources :customers, only: [:index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog_breed.rb
class DogBreed < ApplicationRecord
  has_many :dogs
end

app/controllers/admin/dog_breeds_controller.rb
class Admin::DogBreedsController < ApplicationController
  before_action :authenticate_admin_admin!
  def index
    @dog_breed = DogBreed.new
    @dog_breeds = DogBreed.page(params[:page]).order('created_at DESC').per(10)
    @dog_breed_count = DogBreed.all
  end

  def create
    dog_breed = DogBreed.new(dog_breed_params)
    dog_breed.save
    redirect_to admin_dog_breeds_path
  end

  def destroy
    dog_breed = DogBreed.find(params[:id])
    dog_breed.destroy
    redirect_to admin_dog_breeds_path
  end

  private

  def dog_breed_params
    params.require(:dog_breed).permit(:name)
  end
end

app/helpers/admin/dog_breeds_helper.rb
module Admin::DogBreedsHelper
end

app/views/admin/dog_breeds/index.html.erb
<div class="container">
  <h2>犬種登録</h2>
  全<%= @dog_breed_count.count %>種登録
  <div class="form-group form-inline ">
    <%= form_for @dog_breed, url: admin_dog_breeds_path do |f| %>
      <%= f.text_field :name,class: 'form-control'  %>
      <%=f.submit '登録', class: 'btn btn-outline-secondary' %>
    <% end %>
  </div>

  <h3>犬種一覧</h3>
  <table class="table table-hover bg-white">
	<tbody>
      <% @dog_breeds.each do |dog_breed| %>
        <tr>
		  <th>
		    <%= dog_breed.name %>
		  </th>
      <th>
        <%= link_to '削除', admin_dog_breed_path(dog_breed), method: :delete, data: { confirm: '本当に削除しますか？' },class: 'btn btn-outline-secondary' %>
      </th>
		</tr>
      <% end %>
    </tbody>
  </table>
  <div class="col-md-4 offset-4">
  <%= paginate @dog_breeds %>
</div>
</div>