config/routes.rb
Rails.application.routes.draw do
  root 'public/customers#about'
  namespace :public do
    devise_for :customers
    get '/top', to: 'customers#top', as: "top"
    resources :customers, only: [:show, :edit, :update]
    put '/customers/:id/hide', to: 'customers#hide', as: 'destroy'
    resources :rooms, only: [:create, :show]
    resources :messages, only: [:create, :destroy]
    resources :dogs, only: [:new, :create, :show, :edit, :update, :destroy]
    get '/posts/newimage', to: 'posts#newimage', as: "newimage"
    get '/posts/newvideo', to: 'posts#newvideo', as: "newvideo"
    resources :posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :relationships, only: [:create, :destroy]
    get '/followers', to: 'relationships#followers', as: "followers"
    get '/follows', to: 'relationships#follows', as: 'follows'
    resources :notifications, only: :index
    get '/notification', to: 'notifications#hide', as: 'hide'
    get '/search', to: 'search#search'
  end

  namespace :admin do
    devise_for :admins
    resources :dog_breeds, only: [:index, :create, :destroy]
    resources :customers, only: [:index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :dogs, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :introduction, length: { maximum: 100 }
  # ユーザー理論削除
  def active_for_authentication?
    super && (is_active == "有効")
  end
  enum is_active: { "退会": false, "有効": true }

  # いいね機能
  has_many :favorites, dependent: :destroy
  # DM機能
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries
  # フォロー機能
  has_many :relationships
  # 画像投稿
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :profile_image, ProfileImageUploader
  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header_admin.html.erb
<!-- admin -->
<nav class="navbar navbar-expand-lg navbar-light  displaycol">
  <div class="container">
  <h1 id="title">MyDogs</h1>
      <div class="row">
      <div class="col-md-5 offset-7 ">
        <div class="form-group form-inline ">
          <%= form_tag(public_search_path, method: :get) do %>
            <%= select_tag 'search[model]', options_for_select({"投稿" => "post", "タグ" => "tag", "犬種" => "dog" }),class: 'form-control' %>
            <%= text_field_tag 'search[content]','', class: 'form-control'%>
            <%= submit_tag "検索", class: 'btn btn-outline-secondary' %>
          <% end %>
        </div>
      </div>
        <div class="col-md-2 ">
          <%= link_to public_top_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-home">H O M E</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-paw">投 稿 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(image: "image"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-camera">写 真 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(video: "video"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-play-circle">動 画 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-1 offset-1">
          <div class="dropdown">
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">管理者Menu
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to '犬種追加',admin_dog_breeds_path, class: "dropdown-item"%>
              <%= link_to '会員一覧',admin_customers_path, class: "dropdown-item"%>
              <%= link_to 'ログアウト',destroy_admin_admin_session_path, method: :delete,class: "dropdown-item"  %>
              <%= link_to 'About',root_path,class: "dropdown-item"%>
            </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_header_customer.html.erb
<!-- ログイン有 -->
<nav class="navbar navbar-expand-lg navbar-light  displaycol">
  <div class="container">
	<h1 id="title">MyDogs</h1>
      <div class="row">
	  	<div class="col-md-6 offset-2">
	 	  <p>ようこそ<%= link_to"#{current_public_customer.name}", public_customer_path(current_public_customer) %>さん</p>
		</div>
        <div class="col-md-2 text-right">
          <div class="dropdown">
        	<button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bars" style="color: black;">menu</i>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'ログアウト',destroy_public_customer_session_path, method: :delete,class: "dropdown-item"  %>
              <%= link_to 'マイページ',public_customer_path(current_public_customer),class: "dropdown-item"%>
              <%= link_to 'About',root_path,class: "dropdown-item"%>
            </div>
          </div>
        </div>
        <div class="col-md-1 text-right">
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle fa-xs" style="color: gold;"></i>
          <% end %>
          <%= link_to public_notifications_path do %>
            <i class="far fa-bell fa-lg"></i>
          <% end %>
        </div>

	    <div class="col-md-5 offset-7 ">
	      <div class="form-group form-inline ">
	        <%= form_tag(public_search_path, method: :get) do %>
	          <%= select_tag 'search[model]', options_for_select({"投稿" => "post", "タグ" => "tag", "犬種" => "dog" }),class: 'form-control' %>
	          <%= text_field_tag 'search[content]','', class: 'form-control'%>
	          <%= submit_tag "検索", class: 'btn btn-outline-secondary' %>
	        <% end %>
	      </div>
	    </div>
        <div class="col-md-2 ">
          <%= link_to public_top_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-home">H O M E</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-paw">投 稿 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(image: "image"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-camera">写 真 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(video: "video"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-play-circle">動 画 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-1 offset-1">
      	  <div class="dropdown">
      		<button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              投稿
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to '動画投稿',public_newvideo_path, class: "dropdown-item"%>
              <%= link_to '写真投稿',public_newimage_path, class: "dropdown-item"%>
            </div>
	      </div>
	    </div>
	  </div>
	</div>
</nav>

app/views/layouts/_header_visitor.html.erb
<!-- ログインなし -->
<nav class="navbar navbar-expand-lg navbar-light  displaycol">
  <div class="container">
	<h1 id="title">MyDogs</h1>
      <div class="row">
      	<div class="col-md-2 offset-8">
          <%= link_to '新規登録', new_public_customer_registration_path, class: "nav-link btn btn-outline-secondary" %>
      	</div>
      	<div class="col-md-2 mb-3">
          <%= link_to 'ログイン', new_public_customer_session_path, class: "nav-link btn btn-outline-secondary" %>
      	</div>
	    <div class="col-md-5 offset-7 ">
	      <div class="form-group form-inline ">
	        <%= form_tag(public_search_path, method: :get) do %>
	          <%= select_tag 'search[model]', options_for_select({"投稿" => "post", "タグ" => "tag", "犬種" => "dog" }),class: 'form-control' %>
	          <%= text_field_tag 'search[content]','', class: 'form-control'%>
	          <%= submit_tag "検索", class: 'btn btn-outline-secondary' %>
	        <% end %>
	      </div>
	    </div>
        <div class="col-md-2 ">
          <%= link_to public_top_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-home">H O M E</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to root_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-sticky-note">ABOUT</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path, class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-paw">投 稿 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(image: "image"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-camera">写 真 一 覧</i>
          <% end %>
        </div>
        <div class="col-md-2 ">
          <%= link_to public_posts_path(video: "video"), class: "nav-link text-dark btn btn-outline-secondary btn-block" do%>
            <i class="fas fa-play-circle">動 画 一 覧</i>
          <% end %>
        </div>
	  </div>
	</div>
</nav>

app/views/layouts/_notifications.html.erb
<% if notice || alert %>
<div class="message">
  <div class="notice"><%= notice %></div>
  <div class="alert"><%= alert %></div>
</div>
<% end %>

app/views/layouts/_side_new_posts.html.erb
<!-- サイド　新着投稿一覧 -->
<div class="card">
  <div class="card-body">
    <p class="text-center card-header"><i class="fas fa-dog fa-lg"></i>新着投稿</p>
    <div class="card-text text-center" >
      <% posts.each do |p| %>
        <% if p.image? %>
          <%= link_to public_post_path(p) do %>
            <%= image_tag p.image.url,class: 'side_new_posts_image' %>
          <% end %>
        <% else %>
          <%= link_to public_post_path(p) do %>
            <%= image_tag p.video_url(:screenshot).to_s,class: 'side_new_posts_image' %>
          <% end %>
        <% end %>
      <% end %>
      <div class='text-right'>
        <%= link_to "もっと見る＞", public_posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_side_popular_dogs.html.erb
<div class="card mt-3">
  <div class="card-body">
    <p class="text-center card-header"><i class="fas fa-crown"></i>人気犬ランキング</p>
    <div class="card-text" >
      <% dog_ids.each do |dog_id| %>
        <ul class="list-group list-group-flush">
          <% @dog = Dog.find(dog_id) %>
            <li class="list-group-item ">
              <%= image_tag @dog.cover_image.thumb.url,class: 'side_dogs_cover_image' %>
                <% if @dog.sex == "男の子" %>
                  <%= link_to "#{@dog.name}",public_dog_path(@dog) %>くん
                <% else %>
                  <%= link_to "#{@dog.name}",public_dog_path(@dog) %>ちゃん
                <% end %>
            </li>
      <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/layouts/_side_popular_tags.html.erb
<!-- サイド　人気タグ一覧 -->
<div class="card mt-3">
  <div class="card-body">
    <p class="text-center card-header"><i class="fas fa-tags"></i>人気のタグ</p>
    <div class="card-text text-center" >
      <% popular_tags.each do |t| %>
        <%= link_to"#{t.name}", public_posts_path(tag_name: t.name),class: 'btn btn-outline-dark mt-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/7223783fbe.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
    <header>
      <% if public_customer_signed_in? %>
        <%= render 'layouts/header_customer' %>
        <div class="header-bottom"></div>
      <% elsif admin_admin_signed_in? %>
        <%= render 'layouts/header_admin' %>
      <% else %>
        <%= render 'layouts/header_visitor' %>
        <div class="header-bottom"></div>
      <% end %>
    </header>
    <%= yield %>
      <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center pt-3">
            <p>Copyright © 2020 MyDogs All Rights Reserved.</p>
          </div>
          <div class="col-md-4 offset-4 text-center ">
            S N S
          </div>
          <div class="col-md-4 offset-4 text-center mb-3">
            <a href="https://twitter.com/home">
              <i class="fab fa-twitter-square fa-2x faa-shake animated-hover"></i>
            </a>
            <a href="https://www.instagram.com/?hl=ja">
              <i class="fab fa-instagram-square fa-2x faa-shake animated-hover"></i>
            </a>
            <a href="https://ja-jp.facebook.com/">
              <i class="fab fa-facebook-square fa-2x faa-shake animated-hover"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>
  </div>
  </body>
</html>